apiVersion: v1
kind: Service
metadata:
  name: heavy-fast-api-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: heavy-fast-api
  ports:
    - name: web
      port: 8000
      targetPort: web
      nodePort: 31119